import type { ProviderRule } from "./types";

export const providerRules: ProviderRule[] = [
  {
    id: "proofpoint",
    name: "Proofpoint",
    categories: ["seg"],
    mxPatterns: ["pphosted.com", "proofpoint.com"],
    confidence: "high",
  },
  {
    id: "proofpoint-essentials",
    name: "Proofpoint Essentials",
    categories: ["seg"],
    mxPatterns: ["ppe-hosted.com"],
    confidence: "high",
  },
  {
    id: "mimecast",
    name: "Mimecast",
    categories: ["seg"],
    mxPatterns: ["mimecast.com", "mimecastprotect.com"],
    txtPatterns: ["mimecast.com", "_netblocks.mimecast.com"],
    spfIncludePatterns: ["_netblocks.mimecast.com", "mimecast.com"],
    confidence: "high",
  },
  {
    id: "barracuda",
    name: "Barracuda",
    categories: ["seg"],
    mxPatterns: ["ess.barracudanetworks.com", "barracudanetworks.com"],
    txtPatterns: ["barracudanetworks.com"],
    spfIncludePatterns: ["barracudanetworks.com"],
    confidence: "high",
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365 / EOP",
    categories: ["mailbox", "seg", "outbound_sender"],
    mxPatterns: ["mail.protection.outlook.com"],
    spfIncludePatterns: ["spf.protection.outlook.com"],
    confidence: "high",
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    categories: ["mailbox", "outbound_sender"],
    mxPatterns: ["aspmx.l.google.com", "alt1.aspmx.l.google.com", "alt2.aspmx.l.google.com", "googlemail.com"],
    spfIncludePatterns: ["_spf.google.com"],
    confidence: "high",
  },
  // Consumer mailboxes. These do NOT match the business rules above: gmail.com
  // routes to gmail-smtp-in (not aspmx), and outlook.com/hotmail.com route to
  // olc.protection.outlook.com (not mail.protection.outlook.com). Worth naming
  // separately — a free mailbox in a prospect list means something different
  // from a company on Workspace or 365.
  {
    id: "gmail-consumer",
    name: "Gmail (consumer)",
    categories: ["mailbox"],
    mxPatterns: ["gmail-smtp-in.l.google.com"],
    confidence: "high",
  },
  {
    id: "outlook-consumer",
    name: "Outlook.com / Hotmail",
    categories: ["mailbox"],
    mxPatterns: ["olc.protection.outlook.com"],
    confidence: "high",
  },
  {
    id: "yahoo",
    name: "Yahoo / AOL Mail",
    categories: ["mailbox"],
    mxPatterns: ["yahoodns.net"],
    confidence: "high",
  },
  {
    id: "icloud",
    name: "iCloud Mail",
    categories: ["mailbox"],
    mxPatterns: ["mail.icloud.com"],
    confidence: "high",
  },
  {
    id: "proton",
    name: "Proton Mail",
    categories: ["mailbox"],
    mxPatterns: ["protonmail.ch"],
    confidence: "high",
  },
  {
    id: "zoho",
    name: "Zoho Mail",
    categories: ["mailbox", "outbound_sender"],
    mxPatterns: ["smtpin.zoho.com", "zoho.eu"],
    spfIncludePatterns: ["zoho.com", "zoho.eu"],
    confidence: "high",
  },
  {
    id: "gmx",
    name: "GMX / Mail.com",
    categories: ["mailbox"],
    mxPatterns: ["gmx.net"],
    confidence: "high",
  },
  {
    id: "cisco-secure-email",
    name: "Cisco Secure Email / IronPort",
    categories: ["seg"],
    mxPatterns: ["iphmx.com", "ironport.com"],
    txtPatterns: ["iphmx.com", "ironport.com"],
    spfIncludePatterns: ["iphmx.com"],
    confidence: "high",
  },
  {
    id: "sophos",
    name: "Sophos",
    categories: ["seg"],
    mxPatterns: ["sophos.com", "sophosxl.net"],
    confidence: "high",
  },
  {
    id: "fortinet",
    name: "Fortinet FortiMail",
    categories: ["seg"],
    mxPatterns: ["fortimail", "fortinet.com"],
    confidence: "medium",
  },
  {
    id: "trend-micro",
    name: "Trend Micro Email Security",
    categories: ["seg"],
    mxPatterns: ["trendmicro.com", "trendmicro.eu", "in.tmes.trendmicro.com"],
    confidence: "high",
  },
  {
    id: "cloudflare-area1",
    name: "Cloudflare Area 1",
    categories: ["seg"],
    mxPatterns: ["area1.cloudflare.net", "mx.cloudflare.net"],
    confidence: "high",
  },
  {
    id: "zix-appriver",
    name: "Zix / AppRiver",
    categories: ["seg"],
    mxPatterns: ["appriver.com", "zixcorp.com"],
    txtPatterns: ["appriver.com", "zixcorp.com"],
    spfIncludePatterns: ["appriver.com", "zixcorp.com"],
    confidence: "high",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    categories: ["outbound_sender"],
    spfIncludePatterns: ["sendgrid.net"],
    confidence: "high",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    categories: ["outbound_sender"],
    spfIncludePatterns: ["mailgun.org"],
    confidence: "high",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    categories: ["outbound_sender"],
    spfIncludePatterns: ["servers.mcsv.net", "mailchimp.com"],
    confidence: "high",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    categories: ["outbound_sender"],
    spfIncludePatterns: ["hubspotemail.net"],
    confidence: "high",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    categories: ["outbound_sender"],
    spfIncludePatterns: ["salesforce.com"],
    confidence: "medium",
  },
];
